{{- if not .Values.existingSecret }}
{{- if or .Values.azure.storageConnectionString .Values.azure.textAnalyticsKey .Values.azure.mlApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel-weave.fullname" . }}-azure
  labels:
    {{- include "sentinel-weave.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.azure.storageConnectionString }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.azure.storageConnectionString | quote }}
  {{- end }}
  {{- if .Values.azure.textAnalyticsEndpoint }}
  AZURE_TEXT_ANALYTICS_ENDPOINT: {{ .Values.azure.textAnalyticsEndpoint | quote }}
  {{- end }}
  {{- if .Values.azure.textAnalyticsKey }}
  AZURE_TEXT_ANALYTICS_KEY: {{ .Values.azure.textAnalyticsKey | quote }}
  {{- end }}
  {{- if .Values.azure.appInsightsConnectionString }}
  AZURE_APPINSIGHTS_CONNECTION_STRING: {{ .Values.azure.appInsightsConnectionString | quote }}
  {{- end }}
  {{- if .Values.azure.mlEndpoint }}
  SENTINELWEAVE_AZURE_ENDPOINT: {{ .Values.azure.mlEndpoint | quote }}
  {{- end }}
  {{- if .Values.azure.mlApiKey }}
  SENTINELWEAVE_AZURE_API_KEY: {{ .Values.azure.mlApiKey | quote }}
  {{- end }}
{{- end }}
{{- end }}
