apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel-weave.serviceAccountName" . }}
  labels:
    {{- include "sentinel-weave.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
